/**
 You are given an array of integers a. A new array b is generated by rearranging the elements of a in the following way:

 b[0] is equal to a[0];
 b[1] is equal to the last element of a;
 b[2] is equal to a[1];
 b[3] is equal to the second-last element of a;
 b[4] is equal to a[2];
 b[5] is equal to the third-last element of a;
 and so on.

 Here is how this process works:

 Your task is to determine whether the new array b is sorted in strictly ascending order or not.

 Example

 For a = [1, 3, 5, 6, 4, 2], the output should be alternatingSort(a) = true.

 The new array b will look like [1, 2, 3, 4, 5, 6], which is in strictly ascending order, so the answer is true.

 For a = [1, 4, 5, 6, 3], the output should be alternatingSort(a) = false.

 The new array b will look like [1, 3, 4, 6, 5], which is not in strictly ascending order, so the answer is false.

 Input/Output

 [execution time limit] 4 seconds (js)

 [input] array.integer a

 The given array of integers.

 Guaranteed constraints:
 1 ≤ a.length ≤ 105,
 -109 ≤ a[i] ≤ 109.

 [output] boolean

 A boolean representing whether the new array b will be sorted in strictly ascending order or not.

 */

function alternatingSort(a) {

    const len = a.length;

    for (let i = 1; i < len; ++i) {
        const prevId = getId(i-1, len);
        const currId = getId(i, len);
        const prev = a[prevId];
        const curr = a[currId];

        if (prev >= curr) {
            return false;
        }
    }

    return true;
}


function getId(i, n) {
    if (i % 2 > 0) {
        return n - 1 - Math.floor(i / 2);
    } else {
        return i / 2;
    }
}

const tests = [
    {
        a: [1, 3, 5, 6, 4, 2],

        expectedOutput:

            true
    },
    {

        a: [1, 4, 5, 6, 3],


        expectedOutput:

            false
    },
    {

        a: [1],

        expectedOutput:

            true

    },
    {

        a: [1, 2],

        expectedOutput:

            true

    },
    {


        a: [-89, -47, -38, 39, 82, 87, 40, -9, -41, -68],


        expectedOutput:

            true
    },
    {


        a: [-92, -17, 71, 76, 54, -35],


        expectedOutput:

            true

    },
    {


        a: [-52, 2, 31, 56, 47, 29, -35],


        expectedOutput:

            true
    },
    {


        a: [-97, -51, -8, 25, 44, 70, 98, 77, 68, 31, -5, -36, -80],


        expectedOutput:

            true

    },
    {


        a: [-86, -49, -26, -22, 22, 32, 44, 67, 38, 25, 13, -25, -42, -71],


        expectedOutput:

            true
    },
    {


        a: [-92, -23, 0, 45, 89, 96, 99, 95, 89, 41, -17, -48],


        expectedOutput:

            false
    },
    {


        a: [-37, -31, -8, 88, -10, -33],

        expectedOutput:

            true
    },
    {

        a: [-87, -52, 83, 96, 98, 94, 68, -71],

        expectedOutput:

            true
    },
    {

        a: [-92, 9, 41, 99, 29, -78],


        expectedOutput:

            true
    },
    {

        a: [-91, -84, -67, -44, 9, 70, 88, 37, -11, -67, -72, -87],

        Output:

            false,

        expectedOutput:

            false
    },
    {

        a: [-44, -73, -24, 22, 91, 84, 2, -40, -56],


        expectedOutput:

            false


    },
    {


        a: [-79, -48, -42, 4, 9, 55, 70, 84, 62, 40, 7, -28, -46, -74],



        expectedOutput:

            true
    },
    {


        a: [-27, -81, -7, 21, 33, 52, 23, -6, -10, -71],



        expectedOutput:

            false


    },
    {


        a: [-99, -29, -7, 17, 28, 71, 98, 86, 42, 22, 0, -29, -86],


        expectedOutput:

            false

    },
    {


        a: [-86, 93, 4, 27, 49, 74, 74, -70, 60, 41, 14, -44, -80],



        expectedOutput:

            false

    },
    {


        a: [42, -80, -72, -25, 18, -94, 99, 49, 37, 10, -45, -76, -87],


        expectedOutput:

            false
    },
    {


        a: [-73, -27, 52, 60, 90, 91, 71, 55, 30, -56],



        expectedOutput:

            true
    },
    {

        a: [-98, -82, -70, -49, 58, 26, -69, -79, -98],



        expectedOutput:

            false

    },
];

tests.some((test, id) => {
    const res = alternatingSort(test.a);
    if(test.expectedOutput === res) {
        console.log('____ test #', id, ' OK'); // todo
        return false;
    } else {
        console.log('____ test #', id, ' FALL, exp:', test.expectedOutput, ', return: ', res, test); // todo
        return true;
    }
})

    

