/*
You are implementing your own programming language and you've decided to add support for merging strings. A typical merge function would take two strings s1 and s2, and return the lexicographically smallest result that can be obtained by placing the symbols of s2 between the symbols of s1 in such a way that maintains the relative order of the characters in each string.

For example, if s1 = "super" and s2 = "tower", the result should be merge(s1, s2) = "stouperwer".

You'd like to make your language more unique, so for your merge function, instead of comparing the characters in the usual lexicographical order, you'll compare them based on how many times they occur in their respective strings (fewer occurrences means the character is considered smaller). If the number of occurrences are equal, then the characters should be compared in the usual way. If both number of occurences and characters are equal, you should take the characters from the first string to the result.

Given two strings s1 and s2, return the result of the special merge function you are implementing.

Example

    For s1 = "dce" and s2 = "cccbd", the output should be
    mergeStrings(s1, s2) = "dcecccbd".

All symbols from s1 goes first, because all of them have only 1 occurrence in s1 and c has 3 occurrences in s2.

    For s1 = "super" and s2 = "tower", the output should be
    mergeStrings(s1, s2) = "stouperwer".

Because in both strings all symbols occur only 1 time, strings are merged as usual. You can find explanation for this example on the image in the description.

Input/Output

    [execution time limit] 4 seconds (js)

    [input] string s1

    A string consisting only of lowercase English letters.

    Guaranteed constraints:
    1 ≤ s1.length ≤ 104.

    [input] string s2

    A string consisting only of lowercase English letters.

    Guaranteed constraints:
    1 ≤ s2.length ≤ 104.

    [output] string

    The string that results by merging s1 and s2 using your special merge function.

[JavaScript] Syntax Tips

// Prints help message to the console
// Returns a string
function helloWorld(name) {
    console.log("This prints to the console when you Run Tests");
    return "Hello, " + name;
}


 */

function hashMap(queryTypes, queries) {

}

const tests = [
    {
        queryType:
            ["insert",
                "insert",
                "addToValue",
                "addToKey",
                "get"],
        query:
            [[1, 2],
                [2, 3],
                [2],
                [1],
                [3]],

        output: 5,
    },
    {
        queryType:
            ["insert",
                "addToValue",
                "get",
                "insert",
                "addToKey",
                "addToValue",
                "get"],
        query:
            [[1, 2],
                [2],
                [1],
                [2, 3],
                [1],
                [-1],
                [3]],

        output: 6,
    }, {

        queryType:
            ["addToKey",
                "addToKey",
                "insert",
                "addToValue",
                "addToValue",
                "get",
                "addToKey",
                "insert",
                "addToKey",
                "addToValue"],
        query:
            [[-3],
                [-1],
                [0, -3],
                [3],
                [-1],
                [0],
                [-1],
                [-4, -5],
                [-1],
                [-4]],

        output: -1,
    }, {
        queryType:
            ["insert",
                "insert",
                "addToKey",
                "addToKey",
                "addToKey",
                "insert",
                "addToValue",
                "addToKey",
                "addToKey",
                "get"],
        query:
            [[-5, -2],
                [2, 4],
                [-1],
                [-3],
                [1],
                [3, -2],
                [-4],
                [-2],
                [2],
                [-8]],

        output:

            -6
    }, {

        queryType:
            ["insert",
                "get",
                "insert",
                "addToValue",
                "addToValue",
                "addToValue",
                "insert",
                "addToKey",
                "get",
                "insert"],
        query:
            [[2, 1],
                [2],
                [1, 3],
                [-1],
                [0],
                [3],
                [4, -5],
                [3],
                [4],
                [1, 1]],

        output:

            6
    },
    {
        queryType:
            ["addToValue",
                "addToValue",
                "insert",
                "get",
                "addToKey",
                "insert",
                "insert",
                "insert",
                "addToValue",
                "addToKey"],
        query:
            [[-5],
                [3],
                [3, -3],
                [3],
                [0],
                [-4, 2],
                [0, -3],
                [-2, 4],
                [2],
                [2]],

        output:

            -3
    }, {

        queryType:
            ["addToKey",
                "addToKey",
                "insert",
                "addToKey",
                "addToValue",
                "addToKey",
                "addToValue",
                "insert",
                "get",
                "insert"],
        query:
            [[-1],
                [-3],
                [4, 3],
                [2],
                [2],
                [-2],
                [0],
                [-5, 3],
                [-5],
                [3, -4]],

        output:

            3
    }, {

        queryType:
            ["insert",
                "insert",
                "insert",
                "get",
                "insert",
                "insert",
                "insert",
                "addToKey",
                "insert",
                "insert"],
        query:
            [[3, -4],
                [-4, 3],
                [4, -3],
                [4],
                [-5, 0],
                [-2, -5],
                [2, 2],
                [1],
                [-5, -2],
                [1, 3]],

        output:

            -3

        ,
    }, {

        queryType:
            ["addToValue",
                "addToKey",
                "addToKey",
                "insert",
                "addToValue",
                "addToValue",
                "insert",
                "get",
                "get",
                "insert"],
        query:
            [[-2],
                [-3],
                [0],
                [-3, 1],
                [-2],
                [-4],
                [2, -4],
                [2],
                [2],
                [3, -1]],

        output:

            -8

        ,
    }, {

        queryType:
            ["addToKey",
                "addToValue",
                "insert",
                "addToValue",
                "addToKey",
                "get",
                "insert",
                "addToValue",
                "addToValue",
                "get",
                "insert",
                "addToKey",
                "get",
                "addToKey",
                "addToKey",
                "addToValue",
                "insert",
                "addToValue",
                "get",
                "addToKey",
                "addToKey",
                "insert",
                "addToValue",
                "addToKey",
                "addToValue",
                "insert",
                "get",
                "addToKey",
                "addToValue",
                "get",
                "get",
                "get",
                "addToValue",
                "addToValue",
                "get",
                "get",
                "insert",
                "insert",
                "addToKey",
                "insert",
                "addToValue",
                "addToValue",
                "addToKey",
                "addToValue",
                "addToValue",
                "get",
                "addToValue",
                "addToKey",
                "get",
                "addToValue",
                "insert",
                "get",
                "get",
                "get",
                "addToValue",
                "addToValue",
                "get",
                "addToKey",
                "get",
                "addToKey",
                "addToValue",
                "get",
                "get",
                "addToKey",
                "insert",
                "addToKey",
                "get",
                "addToKey",
                "addToValue",
                "addToKey",
                "insert",
                "addToKey",
                "addToValue",
                "addToKey",
                "addToValue",
                "addToValue",
                "get",
                "get",
                "addToKey",
                "insert",
                "get",
                "get",
                "addToKey",
                "insert",
                "addToKey",
                "addToValue",
                "addToKey",
                "insert",
                "addToValue",
                "get",
                "get",
                "insert",
                "get",
                "get",
                "addToValue",
                "get",
                "addToValue",
                "insert",
                "addToKey",
                "addToValue"],
        query:
            [[32],
                [-4],
                [32, -42],
                [19],
                [-45],
                [-13],
                [29, -29],
                [-50],
                [40],
                [-13],
                [39, -11],
                [-47],
                [-60],
                [16],
                [-14],
                [45],
                [-34, 17],
                [-12],
                [-6],
                [2],
                [-33],
                [-33, -6],
                [40],
                [-14],
                [30],
                [-13, 11],
                [-61],
                [-1],
                [-40],
                [-62],
                [-52],
                [-52],
                [-18],
                [-2],
                [-104],
                [-104],
                [-27, -13],
                [28, -17],
                [-40],
                [39, -1],
                [-40],
                [25],
                [-39],
                [46],
                [27],
                [-51],
                [-33],
                [11],
                [-130],
                [37],
                [37, -20],
                [-95],
                [-95],
                [11],
                [37],
                [-2],
                [-40],
                [-47],
                [-167],
                [13],
                [-41],
                [-164],
                [-206],
                [1],
                [14, 19],
                [23],
                [-92],
                [39],
                [25],
                [-33],
                [-5, -34],
                [-45],
                [23],
                [2],
                [-13],
                [-12],
                [-163],
                [-142],
                [-4],
                [-34, -44],
                [-91],
                [-34],
                [34],
                [-49, -19],
                [9],
                [-24]],

        output:

            1069

        ,
    }, {


        queryType:
            ["addToValue",
                "addToKey",
                "insert",
                "insert",
                "insert",
                "insert",
                "insert",
                "addToKey",
                "addToKey",
                "addToValue",
                "get",
                "addToValue",
                "get",
                "addToKey",
                "addToKey",
                "get",
                "insert",
                "addToValue",
                "get",
                "addToValue",
                "insert",
                "get",
                "addToValue",
                "addToValue",
                "addToKey",
                "addToValue",
                "get",
                "get",
                "addToValue",
                "insert",
                "addToKey",
                "addToValue",
                "insert",
                "addToValue",
                "addToValue",
                "addToKey",
                "get",
                "addToKey",
                "addToValue",
                "addToValue",
                "get",
                "addToKey",
                "get",
                "get",
                "addToKey",
                "addToValue",
                "get",
                "addToValue",
                "get",
                "get",
                "get",
                "addToKey",
                "get",
                "addToValue",
                "addToValue",
                "addToKey",
                "insert",
                "addToKey",
                "insert",
                "insert",
                "addToValue",
                "get",
                "get",
                "get",
                "addToValue",
                "addToKey",
                "insert",
                "addToValue",
                "get",
                "addToValue",
                "addToKey",
                "addToValue",
                "addToValue",
                "get",
                "insert",
                "addToValue",
                "get",
                "addToKey",
                "addToValue",
                "addToKey",
                "insert",
                "get",
                "insert",
                "get",
                "addToValue",
                "get",
                "addToKey",
                "insert",
                "addToKey",
                "addToKey",
                "addToKey",
                "addToValue",
                "get",
                "get",
                "get",
                "insert",
                "addToKey",
                "addToValue",
                "addToKey",
                "insert"],
        query:
            [[-36],
                [-39],
                [8, -45],
                [33, 0],
                [9, -50],
                [-46, 1],
                [-45, -6],
                [-38],
                [-32],
                [-13],
                [-61],
                [48],
                [-61],
                [-12],
                [-23],
                [-151],
                [44, -33],
                [17],
                [-150],
                [-12],
                [-1, -45],
                [-150],
                [48],
                [49],
                [15],
                [32],
                [59],
                [-136],
                [0],
                [8, -45],
                [4],
                [-4],
                [-8, 2],
                [38],
                [-45],
                [-34],
                [-112],
                [-27],
                [-14],
                [-2],
                [-43],
                [-12],
                [-10],
                [-81],
                [-12],
                [0],
                [-22],
                [-11],
                [-163],
                [-22],
                [-93],
                [32],
                [-184],
                [40],
                [36],
                [22],
                [7, -26],
                [15],
                [8, 36],
                [-11, 11],
                [5],
                [-147],
                [-24],
                [-147],
                [35],
                [5],
                [8, 25],
                [47],
                [-143],
                [18],
                [19],
                [30],
                [17],
                [32],
                [37, 18],
                [-16],
                [13],
                [30],
                [-28],
                [30],
                [-32, 12],
                [87],
                [45, 4],
                [-63]],

        output:

            2793

        ,

    },

    {

        queryType:
            ["addToValue",
                "insert",
                "addToValue",
                "addToValue",
                "insert",
                "addToKey",
                "insert",
                "addToKey",
                "get",
                "addToKey",
                "get",
                "get",
                "insert",
                "addToValue",
                "insert",
                "addToValue",
                "addToKey",
                "addToKey",
                "addToValue",
                "get",
                "addToKey",
                "insert",
                "addToValue",
                "addToValue",
                "get",
                "addToKey",
                "addToValue",
                "insert",
                "insert",
                "get",
                "insert",
                "get",
                "addToValue",
                "addToKey",
                "insert",
                "addToValue",
                "addToKey",
                "get",
                "insert",
                "addToValue",
                "get",
                "get",
                "get",
                "addToValue",
                "addToValue",
                "insert",
                "addToValue",
                "get",
                "addToValue",
                "insert",
                "get",
                "insert",
                "get",
                "addToKey",
                "addToKey",
                "addToKey",
                "addToValue",
                "insert",
                "addToKey",
                "addToKey",
                "insert",
                "insert",
                "insert",
                "addToValue",
                "get",
                "addToValue",
                "get",
                "addToKey",
                "get",
                "addToValue",
                "addToValue",
                "addToValue",
                "addToKey",
                "addToValue",
                "addToValue",
                "addToValue",
                "get",
                "insert",
                "insert",
                "addToKey",
                "addToValue",
                "insert",
                "insert",
                "get",
                "addToKey",
                "addToKey",
                "get",
                "addToKey",
                "get",
                "addToKey",
                "addToValue",
                "get",
                "addToKey",
                "insert",
                "get",
                "insert",
                "addToKey",
                "addToValue",
                "addToKey",
                "addToValue"],
        query:
            [[-9],
                [12, 44],
                [32],
                [14],
                [-11, -27],
                [1],
                [-27, -47],
                [-47],
                [-34],
                [-24],
                [-98],
                [-58],
                [-23, -42],
                [34],
                [10, -25],
                [9],
                [6],
                [14],
                [23],
                [-61],
                [-19],
                [34, 3],
                [-46],
                [44],
                [-80],
                [1],
                [23],
                [-41, 43],
                [-38, 41],
                [-41],
                [48, -3],
                [-96],
                [-49],
                [21],
                [-5, -30],
                [-7],
                [-6],
                [27],
                [31, 10],
                [-34],
                [-41],
                [-64],
                [31],
                [20],
                [14],
                [-32, -12],
                [1],
                [-41],
                [42],
                [40, 33],
                [-11],
                [-3, 22],
                [-64],
                [-21],
                [-21],
                [-24],
                [22],
                [32, 13],
                [15],
                [-11],
                [7, -39],
                [-11, -6],
                [-2, -23],
                [9],
                [-88],
                [22],
                [-22],
                [-50],
                [-135],
                [1],
                [35],
                [1],
                [-6],
                [-28],
                [19],
                [0],
                [-141],
                [5, -2],
                [-24, -6],
                [-43]],

        output:

            1354

        ,


    }, {

        queryType:
            ["addToKey",
                "addToValue",
                "insert",
                "addToValue",
                "insert",
                "insert",
                "addToKey",
                "addToValue",
                "insert",
                "get",
                "addToKey",
                "insert",
                "get",
                "get",
                "get",
                "get",
                "insert",
                "addToValue",
                "insert",
                "insert",
                "addToKey",
                "addToKey",
                "addToKey",
                "get",
                "insert",
                "insert",
                "insert",
                "addToValue",
                "insert",
                "addToKey",
                "addToValue",
                "addToKey",
                "get",
                "get",
                "addToKey",
                "get",
                "get",
                "addToValue",
                "addToKey",
                "addToKey",
                "get",
                "addToValue",
                "addToValue",
                "addToKey",
                "addToValue",
                "get",
                "get",
                "get",
                "addToValue",
                "addToValue",
                "get",
                "addToValue",
                "addToValue",
                "addToKey",
                "insert",
                "insert",
                "get",
                "get",
                "addToKey",
                "get",
                "get",
                "addToKey",
                "addToValue",
                "addToKey",
                "addToValue",
                "insert",
                "get",
                "insert",
                "addToValue",
                "get",
                "insert",
                "insert",
                "addToKey",
                "addToValue",
                "insert",
                "insert",
                "insert",
                "get",
                "get",
                "addToValue",
                "insert",
                "get",
                "addToKey",
                "addToKey",
                "addToKey",
                "addToKey",
                "addToValue",
                "insert",
                "addToValue",
                "get",
                "addToKey",
                "addToValue",
                "get",
                "get",
                "addToValue",
                "addToKey",
                "get",
                "addToKey",
                "addToKey",
                "addToKey"],
        query:
            [[-5],
                [23],
                [-17, 23],
                [30],
                [45, 11],
                [25, 37],
                [-40],
                [-36],
                [26, -22],
                [-15],
                [16],
                [24, -37],
                [24],
                [21],
                [-41],
                [-41],
                [19, 38],
                [-34],
                [7, 41],
                [37, 39],
                [0],
                [17],
                [-27],
                [27],
                [-1, 3],
                [8, 7],
                [6, 22],
                [5],
                [49, 20],
                [46],
                [-29],
                [35],
                [90],
                [30],
                [7],
                [115],
                [85],
                [-49],
                [-30],
                [43],
                [98],
                [-6],
                [24],
                [-12],
                [-40],
                [116],
                [121],
                [103],
                [39],
                [49],
                [95],
                [16],
                [-37],
                [25],
                [44, -50],
                [-29, 42],
                [128],
                [44],
                [3],
                [166],
                [126],
                [24],
                [27],
                [-2],
                [-3],
                [24, -24],
                [150],
                [38, -34],
                [-35],
                [150],
                [8, -32],
                [14, 16],
                [-6],
                [-9],
                [-35, 37],
                [-34, 43],
                [-45, 2],
                [147],
                [124]],

        output:

            -563

        ,


    },
    {
        queryType:
            ["insert",
                "addToKey",
                "get",
                "get",
                "addToValue",
                "insert",
                "get",
                "get",
                "get",
                "addToValue",
                "insert",
                "insert",
                "addToValue",
                "addToKey",
                "get",
                "get",
                "get",
                "addToKey",
                "get",
                "insert",
                "addToKey",
                "get",
                "addToValue",
                "addToValue",
                "addToValue",
                "insert",
                "addToValue",
                "addToKey",
                "insert",
                "insert",
                "insert",
                "addToValue",
                "addToKey",
                "addToValue",
                "addToKey",
                "get",
                "addToKey",
                "insert",
                "addToValue",
                "addToKey",
                "addToKey",
                "insert",
                "addToKey",
                "addToValue",
                "addToKey",
                "addToValue",
                "insert",
                "get",
                "addToKey",
                "addToValue",
                "insert",
                "get",
                "insert",
                "addToValue",
                "get",
                "addToKey",
                "addToValue",
                "get",
                "get",
                "addToKey",
                "insert",
                "insert",
                "addToValue",
                "addToValue",
                "addToKey",
                "get",
                "get",
                "get",
                "insert",
                "insert",
                "addToKey",
                "addToValue",
                "insert",
                "addToKey",
                "addToKey",
                "addToValue",
                "addToKey",
                "get",
                "insert",
                "get",
                "insert",
                "insert",
                "insert",
                "addToValue",
                "addToKey",
                "get",
                "addToKey",
                "get",
                "addToValue",
                "addToValue",
                "addToKey",
                "insert",
                "addToValue",
                "addToKey",
                "insert",
                "addToKey",
                "get",
                "get",
                "get",
                "addToKey"],
        query:
            [[-23, 44],
                [-44],
                [-67],
                [-67],
                [-5],
                [-4, 17],
                [-4],
                [-67],
                [-67],
                [-48],
                [-34, -42],
                [-35, 44],
                [-32],
                [-26],
                [-61],
                [-93],
                [-61],
                [-25],
                [-118],
                [17, -13],
                [-29],
                [-12],
                [-41],
                [24],
                [12],
                [38, 28],
                [18],
                [47],
                [-20, -14],
                [18, -15],
                [-41, -50],
                [11],
                [22],
                [5],
                [48],
                [50],
                [-22],
                [-6, -41],
                [-33],
                [-2],
                [-10],
                [-9, 8],
                [-19],
                [-27],
                [-45],
                [22],
                [-33, 4],
                [-65],
                [47],
                [-46],
                [7, 21],
                [-18],
                [9, 47],
                [-50],
                [37],
                [6],
                [29],
                [60],
                [5],
                [40],
                [36, -13],
                [17, -5],
                [49],
                [-50],
                [2],
                [47],
                [0],
                [26],
                [-38, -31],
                [-13, -43],
                [9],
                [-9],
                [-2, -1],
                [4],
                [-48],
                [-5],
                [24],
                [-11],
                [-13, -13],
                [36]],

        output:

            -1605

        ,


    }, {
        queryType:
            ["addToValue",
                "addToValue",
                "insert",
                "insert",
                "insert",
                "addToValue",
                "addToValue",
                "addToKey",
                "get",
                "addToKey",
                "insert",
                "addToKey",
                "addToKey",
                "insert",
                "get",
                "addToValue",
                "addToValue",
                "insert",
                "get",
                "addToValue",
                "addToKey",
                "addToValue",
                "addToValue",
                "get",
                "insert",
                "insert",
                "get",
                "get",
                "get",
                "addToValue",
                "addToKey",
                "addToKey",
                "insert",
                "addToKey",
                "insert",
                "get",
                "get",
                "get",
                "addToKey",
                "insert",
                "addToValue",
                "addToValue",
                "get",
                "addToKey",
                "get",
                "get",
                "addToValue",
                "addToValue",
                "addToValue",
                "insert",
                "addToValue",
                "addToKey",
                "insert",
                "addToValue",
                "get",
                "addToKey",
                "insert",
                "addToValue",
                "addToValue",
                "addToValue",
                "addToValue",
                "get",
                "get",
                "addToKey",
                "insert",
                "insert",
                "addToKey",
                "addToValue",
                "addToKey",
                "addToKey",
                "insert",
                "get",
                "addToValue",
                "addToKey",
                "insert",
                "addToKey",
                "get",
                "get",
                "addToValue",
                "addToValue",
                "get",
                "insert",
                "insert",
                "addToKey",
                "addToValue",
                "insert",
                "addToKey",
                "insert",
                "addToKey",
                "insert",
                "addToKey",
                "addToKey",
                "get",
                "insert",
                "insert",
                "addToValue",
                "get",
                "get",
                "addToValue",
                "addToValue"],
        query:
            [[-10],
                [-32],
                [-37, 32],
                [-45, 26],
                [-25, -23],
                [23],
                [49],
                [-14],
                [-39],
                [15],
                [3, 44],
                [3],
                [-35],
                [40, 22],
                [-56],
                [-34],
                [38],
                [6, -39],
                [-29],
                [1],
                [43],
                [-30],
                [37],
                [-33],
                [-23, 45],
                [-48, -21],
                [-23],
                [49],
                [14],
                [3],
                [28],
                [-29],
                [38, 11],
                [-46],
                [20, 20],
                [-95],
                [-33],
                [-70],
                [-19],
                [-14, 36],
                [16],
                [-42],
                [-79],
                [20],
                [3],
                [6],
                [36],
                [-32],
                [24],
                [7, -12],
                [34],
                [-33],
                [-46, 1],
                [-14],
                [-26],
                [35],
                [-21, -48],
                [-2],
                [-1],
                [41],
                [7],
                [5],
                [-69],
                [5],
                [-40, 33],
                [-48, -20],
                [38],
                [49],
                [48],
                [40],
                [-14, -9],
                [39],
                [42],
                [-25],
                [48, 34],
                [-41],
                [88],
                [-4],
                [-47],
                [-23],
                [12],
                [-45]],

        output: 1456,

    },
]

tests.forEach((test, index) => {
    const sum = hashMap(test.queryType, test.query);

    console.log('!!__ test', index,
        '\n\t expected:', test.output
    );

    if (+sum === test.output) {
        console.log('OK  returned:', sum);
    } else {
        console.log('ERR returned:', sum, '!==', test.output);
    }

    printTest(test);
    console.log('');
})

function printTest(test) {
    test.queryType.forEach((type, id) => {
        console.log(type, test.query[id]); // todo
    });
}